<?php

namespace frontend\models;

use app\models\User;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "case_referer".
 *
 * @property int $id
 * @property string $referer
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 */
class CaseReferer extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'case_referer';
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['referer'], 'required'],
            [['created_at', 'updated_at', 'created_by'], 'integer'],
            [['referer'], 'string', 'max' => 255],
            [['referer'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'referer' => 'Referer',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
        ];
    }

    /**
     * {@inheritdoc}
     * @return CaseRefererQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CaseRefererQuery(get_called_class());
    }

    public function getUser()
    {
        return $this->hasOne(User::className(),['id' => 'created_by']);
    }
}
