<?php

namespace frontend\models;

use app\models\Locations;
use app\models\User;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "court".
 *
 * @property int $id
 * @property string $court
 * @property int|null $location
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 */
class Court extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'court';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['court'], 'required'],
            [['location', 'created_at', 'updated_at', 'created_by','updated_by'], 'integer'],
            [['court'], 'string', 'max' => 255],
            [['court'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'court' => 'Court',
            'location' => 'Location',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
        ];
    }

    /**
     * {@inheritdoc}
     * @return CourtQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CourtQuery(get_called_class());
    }

    public function getCourtLocation()
    {
        return $this->hasOne(CourtLocation::className(),['id' => 'location']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(),['id' => 'created_by']);
    }
}
