<?php

namespace frontend\models;

use app\models\User;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "nature_of_sentence".
 *
 * @property int $id
 * @property string $nature
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property float|null $fine_amount
 */
class NatureOfSentence extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'nature_of_sentence';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nature'], 'required'],
            [['created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['fine_amount'], 'number'],
            [['nature'], 'string', 'max' => 255],
            [['nature'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nature' => 'Nature',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'fine_amount' => 'Fine Amount',
        ];
    }

    /**
     * {@inheritdoc}
     * @return NatureOfSentenceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new NatureOfSentenceQuery(get_called_class());
    }

    public function getCreator() {
        return $this->hasOne(User::className(),['id' => 'created_by']);
    }

    public function getUpdator() {
        return $this->hasOne(User::className(),['id' => 'updated_by']);
    }
}
