<?php

namespace frontend\models;

use common\models\User;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "rck_representation".
 *
 * @property int $id
 * @property string $representation
 * @property string|null $case_category
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class RckRepresentation extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rck_representation';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['representation'], 'required'],
            [['created_by', 'updated_by', 'created_at', 'updated_at'], 'integer'],
            [['representation'], 'string', 'max' => 60],
            [['case_category'], 'string', 'max' => 50],
            [['representation'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'representation' => 'Representation',
            'case_category' => 'Case Category',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * {@inheritdoc}
     * @return RckRepresentationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RckRepresentationQuery(get_called_class());
    }

    public function getCreator()
    {
        return $this->hasOne(User::className(),['id' => 'created_by']);
    }

    public function getUpdator()
    {
        return $this->hasOne(User::className(),['id' => 'updated_by']);
    }
}
