<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "training_attachment_lines".
 *
 * @property int $id
 * @property int|null $training_id
 * @property string|null $description
 * @property string|null $filename
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 */
class TrainingAttachmentLines extends \yii\db\ActiveRecord
{
    public $imageFile;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'training_attachment_lines';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className()
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['training_id', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['description'], 'string', 'max' => 250],
            [['filename'], 'string', 'max' => 255],
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'pdf'],
            [['filename','description'],'unique']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'training_id' => 'Training ID',
            'description' => 'Description',
            'filename' => 'Filename',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'imageFile' => 'Upload Document'
        ];
    }

    /**
     * {@inheritdoc}
     * @return TrainingAttachmentLinesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TrainingAttachmentLinesQuery(get_called_class());
    }

    public function upload()
    {
        if ($this->validate()) {
            $this->imageFile->saveAs('uploads/' .str_replace(' ','',$this->imageFile->name));


            $Path = \yii\helpers\Url::home(true).'uploads/'.str_replace(' ','',$this->imageFile->name); // Readable from nav interface
            $this->filename = $Path;


            return true;
        } else {
            return false;
        }
    }

    public function getCreator()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $this->upload();
        $this->updateAttributes(['filename']);
    }
}
